<a href="https://colab.research.google.com/github/noahbean33/quantum_computing_experiments/blob/main/quantum_monte_carlo_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install cirq --quiet


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 18.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 532.7/532.7 kB 13.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.5/60.5 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.3/69.3 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.5/596.5 kB 19.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.6/202.6 kB 14.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 40.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 5.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 48.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 44.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.8/117.8 kB 6.5 MB/s eta 

In [2]:
import cirq
import numpy as np


In [3]:
def create_quantum_circuit():
    # Create a qubit
    qubit = cirq.GridQubit(0, 0)

    # Create a circuit
    circuit = cirq.Circuit()

    # Apply a Hadamard gate to create a superposition
    circuit.append(cirq.H(qubit))

    # Measure the qubit
    circuit.append(cirq.measure(qubit, key='result'))

    return circuit, qubit


In [4]:
def simulate_quantum_circuit(circuit, repetitions=1000):
    # Create a simulator
    simulator = cirq.Simulator()

    # Run the simulation
    result = simulator.run(circuit, repetitions=repetitions)

    # Extract the measurement results
    measurements = result.measurements['result']

    # Calculate the probabilities
    counts = np.sum(measurements)
    probability_0 = 1 - counts / repetitions
    probability_1 = counts / repetitions

    return probability_0, probability_1


In [5]:
if __name__ == "__main__":
    # Create the quantum circuit
    circuit, qubit = create_quantum_circuit()

    # Print the circuit
    print("Quantum Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    probability_0, probability_1 = simulate_quantum_circuit(circuit, repetitions)

    # Print the results
    print(f"\nResults after {repetitions} repetitions:")
    print(f"Probability of measuring |0⟩: {probability_0:.3f}")
    print(f"Probability of measuring |1⟩: {probability_1:.3f}")


Quantum Circuit:
(0, 0): ───H───M('result')───

Results after 1000 repetitions:
Probability of measuring |0⟩: 0.487
Probability of measuring |1⟩: 0.513


In [6]:
import cirq
import numpy as np

def create_quantum_circuit():
    # Create a qubit
    qubit = cirq.GridQubit(0, 0)

    # Create a circuit
    circuit = cirq.Circuit()

    # Apply a Hadamard gate to create a superposition
    circuit.append(cirq.H(qubit))

    # Measure the qubit
    circuit.append(cirq.measure(qubit, key='result'))

    return circuit, qubit

def simulate_quantum_circuit(circuit, repetitions=1000):
    # Create a simulator
    simulator = cirq.Simulator()

    # Run the simulation
    result = simulator.run(circuit, repetitions=repetitions)

    # Extract the measurement results
    measurements = result.measurements['result']

    # Calculate the probabilities
    counts = np.sum(measurements)
    probability_0 = 1 - counts / repetitions
    probability_1 = counts / repetitions

    return probability_0, probability_1

if __name__ == "__main__":
    # Create the quantum circuit
    circuit, qubit = create_quantum_circuit()

    # Print the circuit
    print("Quantum Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    probability_0, probability_1 = simulate_quantum_circuit(circuit, repetitions)

    # Print the results
    print(f"\nResults after {repetitions} repetitions:")
    print(f"Probability of measuring |0⟩: {probability_0:.3f}")
    print(f"Probability of measuring |1⟩: {probability_1:.3f}")


Quantum Circuit:
(0, 0): ───H───M('result')───

Results after 1000 repetitions:
Probability of measuring |0⟩: 0.519
Probability of measuring |1⟩: 0.481


In [7]:
def create_portfolio_circuit():
    # Create two qubits representing two assets
    qubits = [cirq.GridQubit(0, i) for i in range(2)]

    # Create a circuit
    circuit = cirq.Circuit()

    # Apply Hadamard gates to create a superposition of allocations
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Measure the qubits
    circuit.append([cirq.measure(qubit, key=f'asset_{i}') for i, qubit in enumerate(qubits)])

    return circuit, qubits


In [8]:
def simulate_portfolio_circuit(circuit, repetitions=1000):
    # Create a simulator
    simulator = cirq.Simulator()

    # Run the simulation
    result = simulator.run(circuit, repetitions=repetitions)

    # Extract the measurement results
    measurements = {key: np.array(values).flatten() for key, values in result.measurements.items()}

    return measurements


In [9]:
def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk


In [10]:
def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(simulations['asset_0'].size):
        weights = np.array([simulations['asset_0'][i], simulations['asset_1'][i]])
        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return and portfolio_risk < best_risk:
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk


In [11]:
if __name__ == "__main__":
    # Define returns and covariance matrix for two assets
    expected_returns = np.array([0.1, 0.12])
    cov_matrix = np.array([[0.005, -0.002],
                           [-0.002, 0.004]])

    # Create the quantum circuit
    circuit, qubits = create_portfolio_circuit()

    # Print the circuit
    print("Quantum Portfolio Optimization Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    simulations = simulate_portfolio_circuit(circuit, repetitions)

    # Optimize the portfolio
    best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

    # Print the results
    print("\nOptimized Portfolio:")
    print(f"Best Allocation: {best_allocation}")
    print(f"Expected Return: {best_return:.3f}")
    print(f"Risk (Variance): {best_risk:.3f}")


Quantum Portfolio Optimization Circuit:
(0, 0): ───H───M('asset_0')───

(0, 1): ───H───M('asset_1')───

Optimized Portfolio:
Best Allocation: [0.5 0.5]
Expected Return: 0.110
Risk (Variance): 0.001


<ipython-input-10-f45d433e308d>:8: RuntimeWarning: invalid value encountered in divide
  weights = weights / np.sum(weights)  # Normalize weights to sum to 1


In [12]:
import cirq
import numpy as np

def create_portfolio_circuit():
    # Create two qubits representing two assets
    qubits = [cirq.GridQubit(0, i) for i in range(2)]

    # Create a circuit
    circuit = cirq.Circuit()

    # Apply Hadamard gates to create a superposition of allocations
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Measure the qubits
    circuit.append([cirq.measure(qubit, key=f'asset_{i}') for i, qubit in enumerate(qubits)])

    return circuit, qubits

def simulate_portfolio_circuit(circuit, repetitions=1000):
    # Create a simulator
    simulator = cirq.Simulator()

    # Run the simulation
    result = simulator.run(circuit, repetitions=repetitions)

    # Extract the measurement results
    measurements = {key: np.array(values).flatten() for key, values in result.measurements.items()}

    return measurements

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(simulations['asset_0'].size):
        weights = np.array([simulations['asset_0'][i], simulations['asset_1'][i]])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return and portfolio_risk < best_risk:
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define returns and covariance matrix for two assets
    expected_returns = np.array([0.1, 0.12])
    cov_matrix = np.array([[0.005, -0.002],
                           [-0.002, 0.004]])

    # Create the quantum circuit
    circuit, qubits = create_portfolio_circuit()

    # Print the circuit
    print("Quantum Portfolio Optimization Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    simulations = simulate_portfolio_circuit(circuit, repetitions)

    # Optimize the portfolio
    best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

    # Print the results
    print("\nOptimized Portfolio:")
    print(f"Best Allocation: {best_allocation}")
    print(f"Expected Return: {best_return:.3f}")
    print(f"Risk (Variance): {best_risk:.3f}")


Quantum Portfolio Optimization Circuit:
(0, 0): ───H───M('asset_0')───

(0, 1): ───H───M('asset_1')───

Optimized Portfolio:
Best Allocation: [0. 1.]
Expected Return: 0.120
Risk (Variance): 0.004


In [13]:
import cirq
import numpy as np

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=1000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

if __name__ == "__main__":
    num_qubits = 20  # Adjust based on your hardware capabilities
    circuit = create_large_quantum_circuit(num_qubits)

    print("Quantum Circuit:")
    print(circuit)

    repetitions = 1000
    result = simulate_large_quantum_circuit(circuit, repetitions)

    print("\nSimulation Results:")
    print(result)


Quantum Circuit:
                                                                                                                                                                                                                                                ┌──────────┐                                                                                                                                                                                                                                   ┌──────────┐                                                                                                                                                                                                                                                                                              ┌──────────────┐
(0, 0): ────H───Rx(0.25π)───@────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

In [14]:
import cirq
import numpy as np

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=1000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations)):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    num_qubits = 20  # Number of assets
    expected_returns = np.random.uniform(0.05, 0.15, num_qubits)
    cov_matrix = np.random.uniform(0.001, 0.01, (num_qubits, num_qubits))
    cov_matrix = (cov_matrix + cov_matrix.T) / 2  # Ensure the covariance matrix is symmetric

    # Create the quantum circuit
    circuit = create_large_quantum_circuit(num_qubits)

    # Print the circuit
    print("Quantum Portfolio Optimization Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    result = simulate_large_quantum_circuit(circuit, repetitions)

    # Extract measurements into a dictionary for easier handling
    simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

    # Optimize the portfolio
    best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

    # Print the results
    print("\nOptimized Portfolio:")
    print(f"Best Allocation: {best_allocation}")
    print(f"Expected Return: {best_return:.3f}")
    print(f"Risk (Variance): {best_risk:.3f}")


Quantum Portfolio Optimization Circuit:
                                                                                                                                                                                                                                                ┌──────────┐                                                                                                                                                                                                                                   ┌──────────┐                                                                                                                                                                                                                                                                                              ┌──────────────┐
(0, 0): ────H───Rx(0.25π)───@─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

In [15]:
import cirq
import numpy as np

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=1000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    num_qubits = 20  # Number of assets
    np.random.seed(42)  # For reproducibility
    expected_returns = np.random.uniform(0.05, 0.15, num_qubits)
    cov_matrix = np.random.uniform(0.001, 0.01, (num_qubits, num_qubits))
    cov_matrix = (cov_matrix + cov_matrix.T) / 2  # Ensure the covariance matrix is symmetric

    # Create the quantum circuit
    circuit = create_large_quantum_circuit(num_qubits)

    # Print the circuit
    print("Quantum Portfolio Optimization Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    result = simulate_large_quantum_circuit(circuit, repetitions)

    # Extract measurements into a dictionary for easier handling
    simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

    # Optimize the portfolio
    best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

    # Print the results
    print("\nOptimized Portfolio:")
    print(f"Best Allocation: {best_allocation}")
    print(f"Expected Return: {best_return:.3f}")
    print(f"Risk (Variance): {best_risk:.3f}")


Quantum Portfolio Optimization Circuit:
                                                                                                                                                                                                                                                ┌──────────┐                                                                                                                                                                                                                                   ┌──────────┐                                                                                                                                                                                                                                                                                              ┌──────────────┐
(0, 0): ────H───Rx(0.25π)───@─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

In [17]:
!pip install cirq yfinance numpy pandas --quiet


In [18]:
import cirq
import numpy as np
import pandas as pd
import yfinance as yf

def get_stock_data(tickers, start_date, end_date):
    data = yf.download(tickers, start=start_date, end=end_date)
    return data['Adj Close']

def calculate_returns(data):
    returns = data.pct_change().dropna()
    return returns

def calculate_expected_returns_and_cov_matrix(returns):
    expected_returns = returns.mean()
    cov_matrix = returns.cov()
    return expected_returns, cov_matrix

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=1000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define the stock tickers and the date range
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'FB']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    # Calculate returns
    returns = calculate_returns(stock_data)

    # Calculate expected returns and covariance matrix
    expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
    expected_returns = expected_returns.values
    cov_matrix = cov_matrix.values

    # Create the quantum circuit
    num_qubits = len(tickers)  # Number of assets
    circuit = create_large_quantum_circuit(num_qubits)

    # Print the circuit
    print("Quantum Portfolio Optimization Circuit:")
    print(circuit)

    # Simulate the circuit
    repetitions = 1000
    result = simulate_large_quantum_circuit(circuit, repetitions)

    # Extract measurements into a dictionary for easier handling
    simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

    # Optimize the portfolio
    best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

    # Print the results
    print("\nOptimized Portfolio:")
    print(f"Best Allocation: {best_allocation}")
    print(f"Expected Return: {best_return:.3f}")
    print(f"Risk (Variance): {best_risk:.3f}")


[*********************100%%**********************]  5 of 5 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['FB']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py:10217: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)


Quantum Portfolio Optimization Circuit:
                                                           ┌──────────┐                                               ┌──────────┐                                                     ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@──────────────────────────────────────X────────────────M('qubit_0')───
                           │                                │                         │                                │                         │                                      │
(0, 1): ───H───Rx(0.25π)───X───@───Rx(0.25π)────────────────┼─────────────────────────X───@───Rx(0.25π)────────────────┼─────────────────────────X───@───M('qubit_1')───────────────────┼───────────────────────────────
                               │                            │                             │                            │                     

In [19]:
import cirq
import numpy as np
import pandas as pd
import yfinance as yf

def get_stock_data(tickers, start_date, end_date):
    data = yf.download(tickers, start=start_date, end=end_date)
    valid_tickers = [ticker for ticker in tickers if ticker in data.columns.levels[1]]
    return data['Adj Close'][valid_tickers]

def calculate_returns(data):
    returns = data.pct_change().dropna()
    return returns

def calculate_expected_returns_and_cov_matrix(returns):
    expected_returns = returns.mean()
    cov_matrix = returns.cov()
    return expected_returns, cov_matrix

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=1000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define the stock tickers and the date range
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    # Check if we have valid data
    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        # Calculate returns
        returns = calculate_returns(stock_data)

        # Calculate expected returns and covariance matrix
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        # Create the quantum circuit
        num_qubits = len(expected_returns)  # Number of assets
        circuit = create_large_quantum_circuit(num_qubits)

        # Print the circuit
        print("Quantum Portfolio Optimization Circuit:")
        print(circuit)

        # Simulate the circuit
        repetitions = 1000
        result = simulate_large_quantum_circuit(circuit, repetitions)

        # Extract measurements into a dictionary for easier handling
        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

        # Optimize the portfolio
        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        # Print the results
        print("\nOptimized Portfolio:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")


[*********************100%%**********************]  5 of 5 completed


Quantum Portfolio Optimization Circuit:
                                                           ┌──────────┐                                               ┌──────────┐                                                     ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@──────────────────────────────────────X────────────────M('qubit_0')───
                           │                                │                         │                                │                         │                                      │
(0, 1): ───H───Rx(0.25π)───X───@───Rx(0.25π)────────────────┼─────────────────────────X───@───Rx(0.25π)────────────────┼─────────────────────────X───@───M('qubit_1')───────────────────┼───────────────────────────────
                               │                            │                             │                            │                     

In [20]:
import cirq
import numpy as np
import pandas as pd
import yfinance as yf

def get_stock_data(tickers, start_date, end_date):
    data = yf.download(tickers, start=start_date, end=end_date)
    valid_tickers = [ticker for ticker in tickers if ticker in data['Adj Close'].columns]
    return data['Adj Close'][valid_tickers]

def calculate_returns(data):
    returns = data.pct_change().dropna()
    return returns

def calculate_expected_returns_and_cov_matrix(returns):
    expected_returns = returns.mean()
    cov_matrix = returns.cov()
    return expected_returns, cov_matrix

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=1000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define the stock tickers and the date range
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    # Check if we have valid data
    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        # Calculate returns
        returns = calculate_returns(stock_data)

        # Calculate expected returns and covariance matrix
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        # Create the quantum circuit
        num_qubits = len(expected_returns)  # Number of assets
        circuit = create_large_quantum_circuit(num_qubits)

        # Print the circuit
        print("Quantum Portfolio Optimization Circuit:")
        print(circuit)

        # Simulate the circuit
        repetitions = 1000
        result = simulate_large_quantum_circuit(circuit, repetitions)

        # Extract measurements into a dictionary for easier handling
        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

        # Optimize the portfolio
        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        # Print the results
        print("\nOptimized Portfolio:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")


[*********************100%%**********************]  5 of 5 completed


Quantum Portfolio Optimization Circuit:
                                                           ┌──────────┐                                               ┌──────────┐                                                     ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@──────────────────────────────────────X────────────────M('qubit_0')───
                           │                                │                         │                                │                         │                                      │
(0, 1): ───H───Rx(0.25π)───X───@───Rx(0.25π)────────────────┼─────────────────────────X───@───Rx(0.25π)────────────────┼─────────────────────────X───@───M('qubit_1')───────────────────┼───────────────────────────────
                               │                            │                             │                            │                     

In [21]:
import cirq
import numpy as np
import pandas as pd
import yfinance as yf

def get_stock_data(tickers, start_date, end_date):
    data = yf.download(tickers, start=start_date, end=end_date)
    valid_tickers = [ticker for ticker in tickers if ticker in data['Adj Close'].columns]
    return data['Adj Close'][valid_tickers]

def calculate_returns(data):
    returns = data.pct_change().dropna()
    return returns

def calculate_expected_returns_and_cov_matrix(returns):
    expected_returns = returns.mean()
    cov_matrix = returns.cov()
    return expected_returns, cov_matrix

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=5000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define the stock tickers and the date range
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    # Check if we have valid data
    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        # Calculate returns
        returns = calculate_returns(stock_data)

        # Calculate expected returns and covariance matrix
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        # Print the expected returns and covariance matrix
        print("\nExpected Returns:")
        print(expected_returns)
        print("\nCovariance Matrix:")
        print(cov_matrix)

        # Create the quantum circuit
        num_qubits = len(expected_returns)  # Number of assets
        circuit = create_large_quantum_circuit(num_qubits)

        # Print the circuit
        print("\nQuantum Portfolio Optimization Circuit:")
        print(circuit)

        # Simulate the circuit with increased repetitions
        repetitions = 5000
        result = simulate_large_quantum_circuit(circuit, repetitions)

        # Extract measurements into a dictionary for easier handling
        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

        # Optimize the portfolio
        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        # Print the results
        print("\nOptimized Portfolio:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")



[*********************100%%**********************]  5 of 5 completed



Expected Returns:
[0.00272752 0.00171715 0.00127582 0.00243731 0.00146729]

Covariance Matrix:
[[0.00086541 0.00068339 0.00053604 0.00049759 0.00065314]
 [0.00068339 0.00076614 0.00057573 0.00049589 0.00061135]
 [0.00053604 0.00057573 0.00058769 0.00039679 0.00055991]
 [0.00049759 0.00049589 0.00039679 0.00058853 0.0004785 ]
 [0.00065314 0.00061135 0.00055991 0.0004785  0.00083761]]

Quantum Portfolio Optimization Circuit:
                                                           ┌──────────┐                                               ┌──────────┐                                                     ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@──────────────────────────────────────X────────────────M('qubit_0')───
                           │                                │                         │                                │                         │          

In [22]:
import cirq
import numpy as np
import pandas as pd
import yfinance as yf
import time

def get_stock_data(tickers, start_date, end_date):
    data = yf.download(tickers, start=start_date, end=end_date)
    valid_tickers = [ticker for ticker in tickers if ticker in data['Adj Close'].columns]
    return data['Adj Close'][valid_tickers]

def calculate_returns(data):
    returns = data.pct_change().dropna()
    return returns

def calculate_expected_returns_and_cov_matrix(returns):
    expected_returns = returns.mean()
    cov_matrix = returns.cov()
    return expected_returns, cov_matrix

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=5000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

def classical_monte_carlo(num_assets, returns, cov_matrix, num_samples=5000):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for _ in range(num_samples):
        weights = np.random.random(num_assets)
        weights /= np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define the stock tickers and the date range
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    # Check if we have valid data
    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        # Calculate returns
        returns = calculate_returns(stock_data)

        # Calculate expected returns and covariance matrix
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        # Print the expected returns and covariance matrix
        print("\nExpected Returns:")
        print(expected_returns)
        print("\nCovariance Matrix:")
        print(cov_matrix)

        # Classical Monte Carlo Simulation
        start_time = time.time()
        classical_allocation, classical_return, classical_risk = classical_monte_carlo(len(expected_returns), expected_returns, cov_matrix)
        classical_time = time.time() - start_time

        # Quantum Monte Carlo Simulation
        num_qubits = len(expected_returns)  # Number of assets
        circuit = create_large_quantum_circuit(num_qubits)

        print("\nQuantum Portfolio Optimization Circuit:")
        print(circuit)

        start_time = time.time()
        result = simulate_large_quantum_circuit(circuit, repetitions=5000)
        quantum_time = time.time() - start_time

        # Extract measurements into a dictionary for easier handling
        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        # Print the results
        print("\nClassical Monte Carlo Optimization:")
        print(f"Best Allocation: {classical_allocation}")
        print(f"Expected Return: {classical_return:.3f}")
        print(f"Risk (Variance): {classical_risk:.3f}")
        print(f"Time Taken: {classical_time:.3f} seconds")

        print("\nQuantum Monte Carlo Optimization:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")
        print(f"Time Taken: {quantum_time:.3f} seconds")


[*********************100%%**********************]  5 of 5 completed



Expected Returns:
[0.00272752 0.00171715 0.00127582 0.00243731 0.00146729]

Covariance Matrix:
[[0.00086541 0.00068339 0.00053604 0.00049759 0.00065314]
 [0.00068339 0.00076614 0.00057573 0.00049589 0.00061135]
 [0.00053604 0.00057573 0.00058769 0.00039679 0.00055991]
 [0.00049759 0.00049589 0.00039679 0.00058853 0.0004785 ]
 [0.00065314 0.00061135 0.00055991 0.0004785  0.00083761]]

Quantum Portfolio Optimization Circuit:
                                                           ┌──────────┐                                               ┌──────────┐                                                     ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@──────────────────────────────────────X────────────────M('qubit_0')───
                           │                                │                         │                                │                         │          

In [23]:
import cirq
import numpy as np
import pandas as pd
import yfinance as yf
import time

def get_stock_data(tickers, start_date, end_date):
    data = yf.download(tickers, start=start_date, end=end_date)
    valid_tickers = [ticker for ticker in tickers if ticker in data['Adj Close'].columns]
    return data['Adj Close'][valid_tickers]

def calculate_returns(data):
    returns = data.pct_change().dropna()
    return returns

def calculate_expected_returns_and_cov_matrix(returns):
    expected_returns = returns.mean()
    cov_matrix = returns.cov()
    return expected_returns, cov_matrix

def create_large_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add a few layers of random single-qubit rotations and CNOT gates
    for _ in range(3):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

def simulate_large_quantum_circuit(circuit, repetitions=5000):
    simulator = cirq.Simulator()
    result = simulator.run(circuit, repetitions=repetitions)
    return result

def portfolio_performance(weights, returns, cov_matrix):
    # Calculate portfolio return
    portfolio_return = np.dot(weights, returns)
    # Calculate portfolio risk (variance)
    portfolio_risk = np.dot(weights.T, np.dot(cov_matrix, weights))
    return portfolio_return, portfolio_risk

def optimize_portfolio(simulations, returns, cov_matrix):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for i in range(len(simulations['qubit_0'])):
        weights = np.array([simulations[f'qubit_{j}'][i] for j in range(len(returns))])
        if np.sum(weights) == 0:
            continue  # Skip if the sum of weights is zero

        weights = weights / np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

def classical_monte_carlo(num_assets, returns, cov_matrix, num_samples=5000):
    best_return = -np.inf
    best_risk = np.inf
    best_allocation = None

    for _ in range(num_samples):
        weights = np.random.random(num_assets)
        weights /= np.sum(weights)  # Normalize weights to sum to 1

        portfolio_return, portfolio_risk = portfolio_performance(weights, returns, cov_matrix)

        if portfolio_return > best_return or (portfolio_return == best_return and portfolio_risk < best_risk):
            best_return = portfolio_return
            best_risk = portfolio_risk
            best_allocation = weights

    return best_allocation, best_return, best_risk

if __name__ == "__main__":
    # Define the stock tickers and the date range
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    # Check if we have valid data
    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        # Calculate returns
        returns = calculate_returns(stock_data)

        # Calculate expected returns and covariance matrix
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        # Print the expected returns and covariance matrix
        print("\nExpected Returns:")
        print(expected_returns)
        print("\nCovariance Matrix:")
        print(cov_matrix)

        # Classical Monte Carlo Simulation
        start_time = time.time()
        classical_allocation, classical_return, classical_risk = classical_monte_carlo(len(expected_returns), expected_returns, cov_matrix)
        classical_time = time.time() - start_time

        # Quantum Monte Carlo Simulation
        num_qubits = len(expected_returns)  # Number of assets
        circuit = create_large_quantum_circuit(num_qubits)

        print("\nQuantum Portfolio Optimization Circuit:")
        print(circuit)

        start_time = time.time()
        result = simulate_large_quantum_circuit(circuit, repetitions=5000)
        quantum_time = time.time() - start_time

        # Extract measurements into a dictionary for easier handling
        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}

        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        # Print the results
        print("\nClassical Monte Carlo Optimization:")
        print(f"Best Allocation: {classical_allocation}")
        print(f"Expected Return: {classical_return:.3f}")
        print(f"Risk (Variance): {classical_risk:.3f}")
        print(f"Time Taken: {classical_time:.3f} seconds")

        print("\nQuantum Monte Carlo Optimization:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")
        print(f"Time Taken: {quantum_time:.3f} seconds")


[*********************100%%**********************]  5 of 5 completed



Expected Returns:
[0.00272752 0.00171715 0.00127582 0.00243731 0.00146729]

Covariance Matrix:
[[0.00086541 0.00068339 0.00053604 0.00049759 0.00065314]
 [0.00068339 0.00076614 0.00057573 0.00049589 0.00061135]
 [0.00053604 0.00057573 0.00058769 0.00039679 0.00055991]
 [0.00049759 0.00049589 0.00039679 0.00058853 0.0004785 ]
 [0.00065314 0.00061135 0.00055991 0.0004785  0.00083761]]

Quantum Portfolio Optimization Circuit:
                                                           ┌──────────┐                                               ┌──────────┐                                                     ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───@──────────────────────────────────────X────────────────M('qubit_0')───
                           │                                │                         │                                │                         │          

In [24]:
def create_advanced_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add more layers of single-qubit rotations and CNOT gates for increased complexity
    for _ in range(5):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.ry(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.rz(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

if __name__ == "__main__":
    # Same initial setup as before
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        returns = calculate_returns(stock_data)
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        print("\nExpected Returns:")
        print(expected_returns)
        print("\nCovariance Matrix:")
        print(cov_matrix)

        # Classical Monte Carlo Simulation
        start_time = time.time()
        classical_allocation, classical_return, classical_risk = classical_monte_carlo(len(expected_returns), expected_returns, cov_matrix)
        classical_time = time.time() - start_time

        # Advanced Quantum Monte Carlo Simulation
        num_qubits = len(expected_returns)
        advanced_circuit = create_advanced_quantum_circuit(num_qubits)

        print("\nAdvanced Quantum Portfolio Optimization Circuit:")
        print(advanced_circuit)

        start_time = time.time()
        result = simulate_large_quantum_circuit(advanced_circuit, repetitions=5000)
        quantum_time = time.time() - start_time

        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}
        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        print("\nClassical Monte Carlo Optimization:")
        print(f"Best Allocation: {classical_allocation}")
        print(f"Expected Return: {classical_return:.3f}")
        print(f"Risk (Variance): {classical_risk:.3f}")
        print(f"Time Taken: {classical_time:.3f} seconds")

        print("\nAdvanced Quantum Monte Carlo Optimization:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")
        print(f"Time Taken: {quantum_time:.3f} seconds")


[*********************100%%**********************]  5 of 5 completed



Expected Returns:
[0.00272752 0.00171715 0.00127582 0.00243731 0.00146729]

Covariance Matrix:
[[0.00086541 0.00068339 0.00053604 0.00049759 0.00065314]
 [0.00068339 0.00076614 0.00057573 0.00049589 0.00061135]
 [0.00053604 0.00057573 0.00058769 0.00039679 0.00055991]
 [0.00049759 0.00049589 0.00039679 0.00058853 0.0004785 ]
 [0.00065314 0.00061135 0.00055991 0.0004785  0.00083761]]

Advanced Quantum Portfolio Optimization Circuit:
                                                                                   ┌──────────┐                                                                       ┌──────────┐                                                                       ┌──────────┐                                                                       ┌──────────┐                                                                             ┌─────────────┐
(0, 0): ───H───Rx(0.25π)───Ry(0.25π)───Rz(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───Ry(0.25π)───Rz(0

In [25]:
def create_enhanced_quantum_circuit(num_qubits):
    qubits = [cirq.GridQubit(0, i) for i in range(num_qubits)]
    circuit = cirq.Circuit()

    # Apply Hadamard gates to all qubits
    circuit.append([cirq.H(qubit) for qubit in qubits])

    # Add more layers of single-qubit rotations and CNOT gates for increased complexity
    for _ in range(5):
        circuit.append([cirq.rx(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.ry(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.rz(np.pi / 4).on(qubit) for qubit in qubits])
        circuit.append([cirq.CNOT(qubits[i], qubits[(i+1) % num_qubits]) for i in range(num_qubits)])

    # Apply an additional layer of parameterized gates
    for qubit in qubits:
        circuit.append(cirq.rz(np.pi / 4).on(qubit))
        circuit.append(cirq.ry(np.pi / 4).on(qubit))
        circuit.append(cirq.rx(np.pi / 4).on(qubit))

    # Measure all qubits
    circuit.append([cirq.measure(qubit, key=f'qubit_{i}') for i, qubit in enumerate(qubits)])

    return circuit

if __name__ == "__main__":
    # Same initial setup as before
    tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
    start_date = '2020-01-01'
    end_date = '2021-01-01'

    # Get stock data
    stock_data = get_stock_data(tickers, start_date, end_date)

    if stock_data.empty:
        print("No valid data available. Exiting.")
    else:
        returns = calculate_returns(stock_data)
        expected_returns, cov_matrix = calculate_expected_returns_and_cov_matrix(returns)
        expected_returns = expected_returns.values
        cov_matrix = cov_matrix.values

        print("\nExpected Returns:")
        print(expected_returns)
        print("\nCovariance Matrix:")
        print(cov_matrix)

        # Classical Monte Carlo Simulation
        start_time = time.time()
        classical_allocation, classical_return, classical_risk = classical_monte_carlo(len(expected_returns), expected_returns, cov_matrix)
        classical_time = time.time() - start_time

        # Enhanced Quantum Monte Carlo Simulation
        num_qubits = len(expected_returns)
        enhanced_circuit = create_enhanced_quantum_circuit(num_qubits)

        print("\nEnhanced Quantum Portfolio Optimization Circuit:")
        print(enhanced_circuit)

        start_time = time.time()
        result = simulate_large_quantum_circuit(enhanced_circuit, repetitions=5000)
        quantum_time = time.time() - start_time

        simulations = {f'qubit_{i}': result.measurements[f'qubit_{i}'].flatten() for i in range(num_qubits)}
        best_allocation, best_return, best_risk = optimize_portfolio(simulations, expected_returns, cov_matrix)

        print("\nClassical Monte Carlo Optimization:")
        print(f"Best Allocation: {classical_allocation}")
        print(f"Expected Return: {classical_return:.3f}")
        print(f"Risk (Variance): {classical_risk:.3f}")
        print(f"Time Taken: {classical_time:.3f} seconds")

        print("\nEnhanced Quantum Monte Carlo Optimization:")
        print(f"Best Allocation: {best_allocation}")
        print(f"Expected Return: {best_return:.3f}")
        print(f"Risk (Variance): {best_risk:.3f}")
        print(f"Time Taken: {quantum_time:.3f} seconds")



[*********************100%%**********************]  5 of 5 completed



Expected Returns:
[0.00272752 0.00171715 0.00127582 0.00243731 0.00146729]

Covariance Matrix:
[[0.00086541 0.00068339 0.00053604 0.00049759 0.00065314]
 [0.00068339 0.00076614 0.00057573 0.00049589 0.00061135]
 [0.00053604 0.00057573 0.00058769 0.00039679 0.00055991]
 [0.00049759 0.00049589 0.00039679 0.00058853 0.0004785 ]
 [0.00065314 0.00061135 0.00055991 0.0004785  0.00083761]]

Enhanced Quantum Portfolio Optimization Circuit:
                                                                                   ┌──────────┐                                                                       ┌──────────┐                                                                       ┌──────────┐                                                                       ┌──────────┐                                                                       ┌──────────┐
(0, 0): ───H───Rx(0.25π)───Ry(0.25π)───Rz(0.25π)───@────────────────────────────────X─────────────Rx(0.25π)───Ry(0.25π)───Rz(0.25π)───@